fos_user:
    db_driver: orm
    firewall_name: main
    user_class: LooopCore\CommonsBundle\Entity\User
    group:
        group_class: LooopCore\CommonsBundle\Entity\Group
#    service:
#        user_manager: sonata.user.orm.user_manager


    from_email:
        address:        "%mailer_default_from%"
        sender_name:    "%mailer_default_from_name%"